import { describe, expect, it } from "vitest";
import {
  cpSync,
  existsSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import { HELP_TEXT, isDirectRun, runCli } from "../src/cli.js";

function createIo() {
  const writes = {
    stderr: "",
    stdout: "",
  };

  return {
    io: {
      stderr: {
        write(chunk: string) {
          writes.stderr += chunk;
        },
      },
      stdout: {
        write(chunk: string) {
          writes.stdout += chunk;
        },
      },
    },
    writes,
  };
}

describe("runCli", () => {
  const options = {
    profilesDir: "/profiles",
    version: "1.2.3",
  };

  it("prints help when called without arguments", async () => {
    const { io, writes } = createIo();

    const exitCode = await runCli([], io, options);

    expect(exitCode).toBe(0);
    expect(writes.stdout).toBe(HELP_TEXT);
    expect(writes.stderr).toBe("");
  });

  it("prints help for help flags", async () => {
    for (const flag of ["-h", "--help"]) {
      const { io, writes } = createIo();

      const exitCode = await runCli([flag], io, options);

      expect(exitCode).toBe(0);
      expect(writes.stdout).toBe(HELP_TEXT);
      expect(writes.stderr).toBe("");
    }
  });

  it("prints the package version for version flags", async () => {
    for (const flag of ["-v", "--version"]) {
      const { io, writes } = createIo();

      const exitCode = await runCli([flag], io, options);

      expect(exitCode).toBe(0);
      expect(writes.stdout).toBe("1.2.3\n");
      expect(writes.stderr).toBe("");
    }
  });

  it("fails for unknown arguments", async () => {
    const { io, writes } = createIo();

    const exitCode = await runCli(["explain"], io, options);

    expect(exitCode).toBe(1);
    expect(writes.stdout).toBe("");
    expect(writes.stderr).toBe(
      "Unknown argument: explain\nRun `architect-companion --help` for usage.\n",
    );
  });

  it("prints the effective model for a valid project", async () => {
    const { io, writes } = createIo();
    const projectDir = fileURLToPath(new URL("fixtures/sample-project", import.meta.url));
    const profilesDir = fileURLToPath(new URL("../profiles", import.meta.url));

    const exitCode = await runCli(
      ["inspect", "effective-model", "--project", projectDir, "--profiles", profilesDir],
      io,
      options,
    );

    expect(exitCode).toBe(0);
    expect(JSON.parse(writes.stdout)).toMatchObject({
      profiles: [
        {
          name: "modular-monolith",
          version: "0.2.0",
        },
        {
          name: "typescript",
          version: "0.1.0",
        },
      ],
      project: {
        languages: ["typescript"],
        name: "sample-project",
      },
    });
    expect(writes.stderr).toBe("");
  });

  it("renders selected targets and creates the profile lock for a valid project", async () => {
    const { io, writes } = createIo();
    const projectDir = copySampleProject();
    const profilesDir = fileURLToPath(new URL("../profiles", import.meta.url));

    try {
      const exitCode = await runCli(
        ["render", "--project", projectDir, "--profiles", profilesDir],
        io,
        options,
      );

      expect(exitCode).toBe(0);
      expect(writes.stdout).toBe(
        "created .architect-companion/profile.lock.yml\ncreated AGENTS.md\n",
      );
      expect(writes.stderr).toContain("warning:");
      expect(readFileSync(join(projectDir, "AGENTS.md"), "utf8")).toContain(
        "Generated by Architect Companion",
      );
      expect(
        readFileSync(join(projectDir, ".architect-companion/profile.lock.yml"), "utf8"),
      ).toContain("contentHash: sha256-");
    } finally {
      rmSync(projectDir, { force: true, recursive: true });
    }
  });

  it("renders quietly on a second run when nothing changed", async () => {
    const { io } = createIo();
    const projectDir = copySampleProject();
    const profilesDir = fileURLToPath(new URL("../profiles", import.meta.url));

    try {
      await runCli(["render", "--project", projectDir, "--profiles", profilesDir], io, options);
      const second = createIo();
      const exitCode = await runCli(
        ["render", "--check", "--project", projectDir, "--profiles", profilesDir],
        second.io,
        options,
      );

      expect(exitCode).toBe(0);
      expect(second.writes.stdout).toBe("Generated targets are fresh.\n");
    } finally {
      rmSync(projectDir, { force: true, recursive: true });
    }
  });

  it("fails render --check when generated targets and the profile lock are missing", async () => {
    const { io, writes } = createIo();
    const projectDir = copySampleProject();
    const profilesDir = fileURLToPath(new URL("../profiles", import.meta.url));

    try {
      const exitCode = await runCli(
        ["render", "--check", "--project", projectDir, "--profiles", profilesDir],
        io,
        options,
      );

      expect(exitCode).toBe(1);
      expect(writes.stdout).toBe("");
      expect(writes.stderr).toContain(".architect-companion/profile.lock.yml is stale (missing).");
      expect(writes.stderr).toContain("AGENTS.md is stale (missing).");
      expect(existsSync(join(projectDir, "AGENTS.md"))).toBe(false);
      expect(existsSync(join(projectDir, ".architect-companion/profile.lock.yml"))).toBe(false);
    } finally {
      rmSync(projectDir, { force: true, recursive: true });
    }
  });

  it("fails render when the profile lock is stale", async () => {
    const { io, writes } = createIo();
    const projectDir = copySampleProject();
    const profilesDir = fileURLToPath(new URL("../profiles", import.meta.url));

    try {
      writeFileSync(
        join(projectDir, ".architect-companion/profile.lock.yml"),
        `schemaVersion: 1
profiles:
  - name: modular-monolith
    version: 0.2.0
    contentHash: sha256-0000000000000000000000000000000000000000000000000000000000000000
  - name: typescript
    version: 0.1.0
    contentHash: sha256-0000000000000000000000000000000000000000000000000000000000000000
`,
      );

      const exitCode = await runCli(
        ["render", "--project", projectDir, "--profiles", profilesDir],
        io,
        options,
      );

      expect(exitCode).toBe(1);
      expect(writes.stderr).toContain("content has changed since the lock was written");
      expect(writes.stderr).toContain("upgrade-profile");
      expect(existsSync(join(projectDir, "AGENTS.md"))).toBe(false);
    } finally {
      rmSync(projectDir, { force: true, recursive: true });
    }
  });

  it("creates the profile lock with upgrade-profile when missing", async () => {
    const { io, writes } = createIo();
    const projectDir = copySampleProject();
    const profilesDir = fileURLToPath(new URL("../profiles", import.meta.url));

    try {
      const exitCode = await runCli(
        ["upgrade-profile", "--project", projectDir, "--profiles", profilesDir],
        io,
        options,
      );

      expect(exitCode).toBe(0);
      expect(writes.stdout).toContain("created .architect-companion/profile.lock.yml");
      expect(writes.stdout).toContain("modular-monolith@0.2.0");
      expect(
        readFileSync(join(projectDir, ".architect-companion/profile.lock.yml"), "utf8"),
      ).toContain("contentHash: sha256-");
    } finally {
      rmSync(projectDir, { force: true, recursive: true });
    }
  });

  it("reports a clean doctor report when everything matches", async () => {
    const { io } = createIo();
    const projectDir = copySampleProject();
    const profilesDir = fileURLToPath(new URL("../profiles", import.meta.url));

    try {
      await runCli(
        ["upgrade-profile", "--project", projectDir, "--profiles", profilesDir],
        io,
        options,
      );
      const doctorIo = createIo();
      const exitCode = await runCli(
        ["doctor", "--project", projectDir, "--profiles", profilesDir],
        doctorIo.io,
        options,
      );

      expect(exitCode).toBe(0);
      expect(doctorIo.writes.stdout).toContain(
        "profile lock: matches modular-monolith@0.2.0, typescript@0.1.0",
      );
      expect(doctorIo.writes.stdout).toContain("tools: all required external tools are reachable");
    } finally {
      rmSync(projectDir, { force: true, recursive: true });
    }
  });

  it("reports a missing tool from doctor when its target requires it", async () => {
    const { io, writes } = createIo();
    const projectDir = copySampleProject();
    const profilesDir = fileURLToPath(new URL("../profiles", import.meta.url));

    try {
      writeFileSync(
        join(projectDir, ".architect-companion/harness.yml"),
        `schemaVersion: 1
profiles:
  - name: modular-monolith
    version: 0.2.0
  - name: typescript
    version: 0.1.0
project:
  name: sample-project
  languages:
    - typescript
boundaries: architecture/boundaries.yml
targets:
  agentsMd: false
  dependencyCruiser: true
`,
      );

      const exitCode = await runCli(
        ["doctor", "--project", projectDir, "--profiles", profilesDir],
        io,
        options,
      );

      expect(exitCode).toBe(1);
      expect(writes.stdout).toContain("tools: 1 missing");
      expect(writes.stdout).toContain("depcruise");
      expect(writes.stdout).toContain("node_modules");
    } finally {
      rmSync(projectDir, { force: true, recursive: true });
    }
  });

  it("fails inspect with useful validation errors", async () => {
    const { io, writes } = createIo();
    const projectDir = mkdtempSync(join(tmpdir(), "architect-companion-empty-"));
    const profilesDir = fileURLToPath(new URL("../profiles", import.meta.url));

    try {
      const exitCode = await runCli(
        ["inspect", "effective-model", "--project", projectDir, "--profiles", profilesDir],
        io,
        options,
      );

      expect(exitCode).toBe(1);
      expect(writes.stdout).toBe("");
      expect(writes.stderr).toContain("harness.yml: file not found.");
    } finally {
      rmSync(projectDir, { force: true, recursive: true });
    }
  });

  it("rejects missing inspect option values before loading files", async () => {
    const { io, writes } = createIo();

    const exitCode = await runCli(
      ["inspect", "effective-model", "--project", "--profiles", "profiles"],
      io,
      options,
    );

    expect(exitCode).toBe(1);
    expect(writes.stdout).toBe("");
    expect(writes.stderr).toBe(
      "--project requires a directory.\nRun `architect-companion --help` for usage.\n",
    );
  });

  it("render --json creates lock and outputs JSON with all results", async () => {
    const { io, writes } = createIo();
    const projectDir = copySampleProject();
    const profilesDir = fileURLToPath(new URL("../profiles", import.meta.url));

    try {
      const exitCode = await runCli(
        ["render", "--json", "--project", projectDir, "--profiles", profilesDir],
        io,
        options,
      );

      expect(exitCode).toBe(0);
      expect(writes.stderr).toBe("");
      const output = JSON.parse(writes.stdout) as unknown;
      expect(output).toMatchObject({
        lockFile: { status: "created" },
        results: expect.arrayContaining([
          expect.objectContaining({ status: "created", target: "agentsMd" }),
        ]),
      });
      expect((output as { warnings: unknown[] }).warnings).toBeInstanceOf(Array);
    } finally {
      rmSync(projectDir, { force: true, recursive: true });
    }
  });

  it("render --json outputs fresh lockFile status on second run", async () => {
    const { io } = createIo();
    const projectDir = copySampleProject();
    const profilesDir = fileURLToPath(new URL("../profiles", import.meta.url));

    try {
      await runCli(["render", "--project", projectDir, "--profiles", profilesDir], io, options);
      const second = createIo();
      const exitCode = await runCli(
        ["render", "--json", "--project", projectDir, "--profiles", profilesDir],
        second.io,
        options,
      );

      expect(exitCode).toBe(0);
      const output = JSON.parse(second.writes.stdout) as unknown;
      expect(output).toMatchObject({ lockFile: { status: "fresh" } });
      expect(
        (output as { results: { status: string }[] }).results.every(
          (r) => r.status === "unchanged",
        ),
      ).toBe(true);
    } finally {
      rmSync(projectDir, { force: true, recursive: true });
    }
  });

  it("render --check --json reports fresh:true when everything is up to date", async () => {
    const { io } = createIo();
    const projectDir = copySampleProject();
    const profilesDir = fileURLToPath(new URL("../profiles", import.meta.url));

    try {
      await runCli(["render", "--project", projectDir, "--profiles", profilesDir], io, options);
      const second = createIo();
      const exitCode = await runCli(
        ["render", "--check", "--json", "--project", projectDir, "--profiles", profilesDir],
        second.io,
        options,
      );

      expect(exitCode).toBe(0);
      expect(second.writes.stderr).toBe("");
      expect(JSON.parse(second.writes.stdout)).toMatchObject({
        fresh: true,
        lockFile: { status: "fresh" },
        results: [],
      });
    } finally {
      rmSync(projectDir, { force: true, recursive: true });
    }
  });

  it("render --check --json reports fresh:false with stale results when targets are missing", async () => {
    const { io, writes } = createIo();
    const projectDir = copySampleProject();
    const profilesDir = fileURLToPath(new URL("../profiles", import.meta.url));

    try {
      const exitCode = await runCli(
        ["render", "--check", "--json", "--project", projectDir, "--profiles", profilesDir],
        io,
        options,
      );

      expect(exitCode).toBe(1);
      expect(writes.stderr).toBe("");
      const output = JSON.parse(writes.stdout) as unknown;
      expect(output).toMatchObject({
        fresh: false,
        lockFile: { status: "stale" },
      });
      expect(
        (output as { results: { status: string }[] }).results.every((r) => r.status === "stale"),
      ).toBe(true);
    } finally {
      rmSync(projectDir, { force: true, recursive: true });
    }
  });

  it("render --json writes error JSON to stderr when profile lock is stale", async () => {
    const { io, writes } = createIo();
    const projectDir = copySampleProject();
    const profilesDir = fileURLToPath(new URL("../profiles", import.meta.url));

    try {
      writeFileSync(
        join(projectDir, ".architect-companion/profile.lock.yml"),
        `schemaVersion: 1
profiles:
  - name: modular-monolith
    version: 0.2.0
    contentHash: sha256-0000000000000000000000000000000000000000000000000000000000000000
  - name: typescript
    version: 0.1.0
    contentHash: sha256-0000000000000000000000000000000000000000000000000000000000000000
`,
      );

      const exitCode = await runCli(
        ["render", "--json", "--project", projectDir, "--profiles", profilesDir],
        io,
        options,
      );

      expect(exitCode).toBe(1);
      expect(writes.stdout).toBe("");
      const error = JSON.parse(writes.stderr) as unknown;
      expect(error).toMatchObject({ error: expect.stringContaining("upgrade-profile") });
    } finally {
      rmSync(projectDir, { force: true, recursive: true });
    }
  });

  it("doctor --json outputs structured report with hasIssues:false when healthy", async () => {
    const { io } = createIo();
    const projectDir = copySampleProject();
    const profilesDir = fileURLToPath(new URL("../profiles", import.meta.url));

    try {
      await runCli(
        ["upgrade-profile", "--project", projectDir, "--profiles", profilesDir],
        io,
        options,
      );
      const doctorIo = createIo();
      const exitCode = await runCli(
        ["doctor", "--json", "--project", projectDir, "--profiles", profilesDir],
        doctorIo.io,
        options,
      );

      expect(exitCode).toBe(0);
      expect(doctorIo.writes.stderr).toBe("");
      const output = JSON.parse(doctorIo.writes.stdout) as unknown;
      expect(output).toMatchObject({
        capabilityWarnings: expect.any(Array),
        hasIssues: false,
        missingTools: [],
        profileLock: { kind: "match" },
      });
    } finally {
      rmSync(projectDir, { force: true, recursive: true });
    }
  });

  it("doctor --json outputs hasIssues:true and profileLock.kind:missing when lock is absent", async () => {
    const { io, writes } = createIo();
    const projectDir = copySampleProject();
    const profilesDir = fileURLToPath(new URL("../profiles", import.meta.url));

    try {
      const exitCode = await runCli(
        ["doctor", "--json", "--project", projectDir, "--profiles", profilesDir],
        io,
        options,
      );

      expect(exitCode).toBe(0);
      expect(writes.stderr).toBe("");
      const output = JSON.parse(writes.stdout) as unknown;
      expect(output).toMatchObject({
        hasIssues: false,
        profileLock: { kind: "missing" },
      });
    } finally {
      rmSync(projectDir, { force: true, recursive: true });
    }
  });

  it("upgrade-profile --json outputs action:created when lock is missing", async () => {
    const { io, writes } = createIo();
    const projectDir = copySampleProject();
    const profilesDir = fileURLToPath(new URL("../profiles", import.meta.url));

    try {
      const exitCode = await runCli(
        ["upgrade-profile", "--json", "--project", projectDir, "--profiles", profilesDir],
        io,
        options,
      );

      expect(exitCode).toBe(0);
      expect(writes.stderr).toBe("");
      expect(JSON.parse(writes.stdout)).toMatchObject({
        action: "created",
        profiles: expect.arrayContaining([expect.objectContaining({ name: "modular-monolith" })]),
      });
    } finally {
      rmSync(projectDir, { force: true, recursive: true });
    }
  });

  it("upgrade-profile --json outputs action:rewrote when lock already matches", async () => {
    const { io } = createIo();
    const projectDir = copySampleProject();
    const profilesDir = fileURLToPath(new URL("../profiles", import.meta.url));

    try {
      await runCli(
        ["upgrade-profile", "--project", projectDir, "--profiles", profilesDir],
        io,
        options,
      );
      const second = createIo();
      const exitCode = await runCli(
        ["upgrade-profile", "--json", "--project", projectDir, "--profiles", profilesDir],
        second.io,
        options,
      );

      expect(exitCode).toBe(0);
      expect(JSON.parse(second.writes.stdout)).toMatchObject({ action: "rewrote" });
    } finally {
      rmSync(projectDir, { force: true, recursive: true });
    }
  });

  it("init --json fails with unknown argument error", async () => {
    const { io, writes } = createIo();

    const exitCode = await runCli(["init", "--json"], io, options);

    expect(exitCode).toBe(1);
    expect(writes.stdout).toBe("");
    expect(writes.stderr).toContain("Unknown argument: --json");
  });

  it("detects direct execution through a package manager symlink", () => {
    const cliPath = fileURLToPath(new URL("../src/cli.ts", import.meta.url));
    const tempDir = mkdtempSync(join(tmpdir(), "architect-companion-"));
    const binPath = join(tempDir, "architect-companion");

    try {
      symlinkSync(cliPath, binPath);

      expect(isDirectRun(pathToFileURL(cliPath).href, binPath)).toBe(true);
    } finally {
      rmSync(tempDir, { force: true, recursive: true });
    }
  });
});

function copySampleProject(): string {
  const projectDir = mkdtempSync(join(tmpdir(), "architect-companion-cli-"));
  cpSync(fileURLToPath(new URL("fixtures/sample-project", import.meta.url)), projectDir, {
    recursive: true,
  });
  return projectDir;
}
