import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";

import {
  DEPENDENCY_CRUISER_TARGET_FILE,
  createDependencyCruiserConfig,
  dependencyCruiserImplementationContract,
  getDependencyCruiserCommandMetadata,
  mapDependencyCruiserJsonResult,
  renderDependencyCruiserConfig,
} from "../src/integrations/dependency-cruiser.js";
import { loadEffectiveHarnessModel } from "../src/model/effective-model.js";

const profilesDir = fileURLToPath(new URL("../profiles", import.meta.url));
const sampleProjectDir = fileURLToPath(new URL("fixtures/sample-project", import.meta.url));
const depcruiseBin = fileURLToPath(
  new URL(
    `../node_modules/.bin/depcruise${process.platform === "win32" ? ".cmd" : ""}`,
    import.meta.url,
  ),
);

describe("dependency-cruiser integration", () => {
  it("declares the policy implementation contract", () => {
    expect(dependencyCruiserImplementationContract).toEqual({
      engine: "dependency-cruiser",
      language: "typescript",
      renderer: "dependency-cruiser-config",
    });
  });

  it("creates dependency-cruiser rules from boundary metadata", async () => {
    const model = await loadEffectiveHarnessModel({
      profilesDir,
      projectDir: sampleProjectDir,
    });

    const config = createDependencyCruiserConfig(model);

    expect(config.forbidden).toEqual([
      {
        comment: "billing may depend on identity only through src/modules/identity/index.ts.",
        from: {
          path: "^src/modules/billing(?:/|$)",
        },
        name: "architect-companion/modular-monolith.module-boundaries/billing-to-identity/internal-import",
        severity: "error",
        to: {
          path: "^(?!src/modules/identity/index\\.ts$)src/modules/identity(?:/|$)",
        },
      },
      {
        comment: "identity does not declare billing as an allowed boundary dependency.",
        from: {
          path: "^src/modules/identity(?:/|$)",
        },
        name: "architect-companion/modular-monolith.module-boundaries/identity-to-billing/undeclared-dependency",
        severity: "error",
        to: {
          path: "^src/modules/billing(?:/|$)",
        },
      },
    ]);
    expect(config.options).toMatchObject({
      combinedDependencies: true,
      doNotFollow: {
        path: ["node_modules"],
      },
      tsPreCompilationDeps: true,
    });
  });

  it("renders a generated CommonJS dependency-cruiser config", async () => {
    const model = await loadEffectiveHarnessModel({
      profilesDir,
      projectDir: sampleProjectDir,
    });

    const source = renderDependencyCruiserConfig(model);

    expect(source).toContain(
      "// Generated by Architect Companion. Edit .architect-companion/ instead.",
    );
    expect(source).toContain("/** @type {import('dependency-cruiser').IConfiguration} */");
    expect(source).toContain("module.exports = ");
    expect(source).toContain(
      '"architect-companion/modular-monolith.module-boundaries/billing-to-identity/internal-import"',
    );
  });

  it("describes how to run dependency-cruiser and map its JSON output", async () => {
    const model = await loadEffectiveHarnessModel({
      profilesDir,
      projectDir: sampleProjectDir,
    });

    expect(getDependencyCruiserCommandMetadata(model)).toEqual({
      args: [
        "--config",
        ".dependency-cruiser.cjs",
        "--output-type",
        "json",
        "src/modules/billing",
        "src/modules/identity",
      ],
      configFile: ".dependency-cruiser.cjs",
      engine: "dependency-cruiser",
      executable: "depcruise",
      inputPaths: ["src/modules/billing", "src/modules/identity"],
      outputType: "json",
      resultMapper: "dependency-cruiser-json",
    });

    const mapped = mapDependencyCruiserJsonResult({
      modules: [],
      summary: {
        error: 1,
        info: 0,
        optionsUsed: {},
        totalCruised: 2,
        violations: [
          {
            from: "src/modules/billing/service.ts",
            rule: {
              comment: "billing may depend on identity only through src/modules/identity/index.ts.",
              name: "architect-companion/modular-monolith.module-boundaries/billing-to-identity/internal-import",
              severity: "error",
            },
            to: "src/modules/identity/internal/customer-repository.ts",
          },
        ],
        warn: 0,
      },
    });

    expect(mapped).toEqual({
      engine: "dependency-cruiser",
      ok: false,
      summary: {
        advisory: 0,
        error: 1,
        totalCruised: 2,
        warning: 0,
      },
      violations: [
        {
          engine: "dependency-cruiser",
          from: "src/modules/billing/service.ts",
          message: "billing may depend on identity only through src/modules/identity/index.ts.",
          policyId: "modular-monolith.module-boundaries",
          rawSeverity: "error",
          ruleName:
            "architect-companion/modular-monolith.module-boundaries/billing-to-identity/internal-import",
          severity: "error",
          to: "src/modules/identity/internal/customer-repository.ts",
        },
      ],
    });

    expect(
      mapDependencyCruiserJsonResult({
        modules: [],
        summary: {
          error: 0,
          info: 0,
          totalCruised: 2,
          violations: [
            {
              from: "src/modules/billing/service.ts",
              rule: {
                name: "architect-companion/modular-monolith.module-boundaries/billing-to-identity/internal-import",
                severity: "warn",
              },
              to: "src/modules/identity/internal/customer-repository.ts",
            },
          ],
          warn: 1,
        },
      }),
    ).toMatchObject({
      ok: false,
      summary: {
        error: 0,
        warning: 1,
      },
      violations: [
        {
          severity: "warning",
        },
      ],
    });
  });

  it("detects a TypeScript module boundary violation with dependency-cruiser", async () => {
    const model = await loadEffectiveHarnessModel({
      profilesDir,
      projectDir: sampleProjectDir,
    });
    const projectDir = mkdtempSync(join(tmpdir(), "architect-companion-depcruise-"));

    try {
      writeDependencyCruiserFixture(projectDir, renderDependencyCruiserConfig(model));
      writeFileSync(
        join(projectDir, "src/modules/billing/service.ts"),
        `import { loadCustomerRow } from "../identity/internal/customer-repository";

export function invoiceCustomer(customerId: string): string {
  return loadCustomerRow(customerId).id;
}
`,
      );

      const result = runDependencyCruiser(
        projectDir,
        getDependencyCruiserCommandMetadata(model).args,
      );
      expect(result.status).toBe(0);

      const mapped = mapDependencyCruiserJsonResult(JSON.parse(result.stdout));
      expect(mapped.ok).toBe(false);
      expect(mapped.violations).toEqual(
        expect.arrayContaining([
          expect.objectContaining({
            from: "src/modules/billing/service.ts",
            policyId: "modular-monolith.module-boundaries",
            ruleName:
              "architect-companion/modular-monolith.module-boundaries/billing-to-identity/internal-import",
            severity: "error",
            to: "src/modules/identity/internal/customer-repository.ts",
          }),
        ]),
      );

      writeFileSync(
        join(projectDir, "src/modules/billing/service.ts"),
        `import { findCustomer } from "../identity";

export function invoiceCustomer(customerId: string): string {
  return findCustomer(customerId);
}
`,
      );

      const allowedResult = runDependencyCruiser(
        projectDir,
        getDependencyCruiserCommandMetadata(model).args,
      );
      expect(allowedResult.status).toBe(0);
      expect(mapDependencyCruiserJsonResult(JSON.parse(allowedResult.stdout)).violations).toEqual(
        [],
      );
    } finally {
      rmSync(projectDir, { force: true, recursive: true });
    }
  });
});

function writeDependencyCruiserFixture(projectDir: string, configSource: string): void {
  mkdirSync(join(projectDir, "src/modules/billing"), { recursive: true });
  mkdirSync(join(projectDir, "src/modules/identity/internal"), { recursive: true });
  writeFileSync(join(projectDir, DEPENDENCY_CRUISER_TARGET_FILE), configSource);
  writeFileSync(
    join(projectDir, "src/modules/identity/index.ts"),
    `export function findCustomer(customerId: string): string {
  return customerId;
}
`,
  );
  writeFileSync(
    join(projectDir, "src/modules/identity/internal/customer-repository.ts"),
    `export function loadCustomerRow(customerId: string): { id: string } {
  return { id: customerId };
}
`,
  );
}

function runDependencyCruiser(
  projectDir: string,
  args: string[],
): {
  status: number | null;
  stdout: string;
} {
  const result = spawnSync(depcruiseBin, args, {
    cwd: projectDir,
    encoding: "utf8",
    shell: process.platform === "win32",
  });

  if (result.error !== undefined) {
    throw result.error;
  }

  return {
    status: result.status,
    stdout: result.stdout,
  };
}
