import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";
import { parse as parseYaml } from "yaml";

import { loadEffectiveHarnessModel } from "../src/model/effective-model.js";
import {
  PR_AGENT_CONFIG_PATH,
  PR_AGENT_WORKFLOW_PATH,
  renderPrAgentConfig,
  renderPrAgentReviewWorkflow,
  renderPrAgentTarget,
} from "../src/renderers/pr-agent.js";
import { getTargetMetadata } from "../src/targets/target-registry.js";

const profilesDir = fileURLToPath(new URL("../profiles", import.meta.url));
const cliProjectDir = fileURLToPath(new URL("fixtures/projects/cli-ts", import.meta.url));

type Model = Awaited<ReturnType<typeof loadEffectiveHarnessModel>>;

async function loadCliModel(): Promise<Model> {
  return loadEffectiveHarnessModel({ profilesDir, projectDir: cliProjectDir });
}

function withDependencyCruiser(model: Model, enabled: boolean): Model {
  return { ...model, targets: { ...model.targets, dependencyCruiser: enabled } };
}

describe("renderPrAgentConfig", () => {
  it("projects the judgment-only rubric into PR-Agent extra_instructions", async () => {
    const config = renderPrAgentConfig(await loadCliModel());

    expect(config).toContain("Generated by Architect Companion");
    expect(config).toContain("[pr_reviewer]");
    expect(config).toContain("extra_instructions = '''");
    // Principles and heuristics are always judgment-only.
    expect(config).toContain("Treat the CLI layer as a thin adapter");
    expect(config).toContain("Error handling review:");
    // Policies without an active engine remain the AI's to judge.
    expect(config).toContain("[cli.cli-entrypoint-responsibility]");
  });

  it("defers machine-enforced policies when their engine target is selected", async () => {
    const config = renderPrAgentConfig(withDependencyCruiser(await loadCliModel(), true));

    expect(config).toContain("do NOT re-review these");
    expect(config).toContain(
      "Layer boundaries [cli.layer-boundaries] — enforced by dependency-cruiser",
    );
    // The deferred policy must not also appear as an AI-owned policy intent.
    expect(config).not.toContain("Layer boundaries [cli.layer-boundaries] (severity: error)");
  });

  it("reclaims those policies for the AI when the engine target is off", async () => {
    const config = renderPrAgentConfig(withDependencyCruiser(await loadCliModel(), false));

    expect(config).not.toContain("do NOT re-review these");
    expect(config).toContain("Layer boundaries [cli.layer-boundaries] (severity: error)");
  });
});

describe("renderPrAgentReviewWorkflow", () => {
  it("renders a model-agnostic advisory workflow pinned to a PR-Agent release", async () => {
    const workflow = renderPrAgentReviewWorkflow(await loadCliModel());
    const parsed = parseYaml(workflow) as {
      jobs: Record<
        string,
        {
          permissions: Record<string, string>;
          steps: { uses: string; env: Record<string, string> }[];
        }
      >;
      on: Record<string, unknown>;
    };

    expect(workflow).toContain("Generated by Architect Companion");
    expect(parsed.on).toHaveProperty("pull_request");
    const job = parsed.jobs["pr-architecture-review"];
    expect(job?.permissions["pull-requests"]).toBe("write");

    const step = job?.steps[0];
    expect(step?.uses).toBe("qodo-ai/pr-agent@v0.36.1");
    // Provider and key come from repo configuration, not a hard-coded vendor.
    expect(step?.env["config.model"]).toBe("${{ vars.PR_AGENT_MODEL }}");
    expect(step?.env["ANTHROPIC.KEY"]).toBe("${{ secrets.LLM_API_KEY }}");
    expect(step?.env.OPENAI_KEY).toBe("${{ secrets.LLM_API_KEY }}");
  });
});

describe("renderPrAgentTarget", () => {
  it("returns outputs in the order declared by the target registry", async () => {
    const outputs = renderPrAgentTarget(await loadCliModel());
    const metadata = getTargetMetadata("prAgent");

    expect(outputs).toHaveLength(metadata.outputs.length);
    expect(metadata.outputs.map((output) => output.outputPath)).toEqual([
      PR_AGENT_CONFIG_PATH,
      PR_AGENT_WORKFLOW_PATH,
    ]);
    expect(outputs[0]).toContain("[pr_reviewer]");
    expect(outputs[1]).toContain("qodo-ai/pr-agent");
  });
});
