import { describe, expect, it } from "vitest";
import { fileURLToPath } from "node:url";

import { loadEffectiveHarnessModel } from "../src/model/effective-model.js";
import {
  GITHUB_ACTIONS_WORKFLOW_PATH,
  renderGitHubActionsWorkflow,
} from "../src/renderers/github-actions.js";

const profilesDir = fileURLToPath(new URL("../profiles", import.meta.url));
const sampleProjectDir = fileURLToPath(new URL("fixtures/sample-project", import.meta.url));

describe("renderGitHubActionsWorkflow", () => {
  it("renders a deterministic GitHub Actions workflow for architecture checks", async () => {
    const model = await loadEffectiveHarnessModel({
      profilesDir,
      projectDir: sampleProjectDir,
    });

    const workflow = renderGitHubActionsWorkflow(withDependencyCruiserEnabled(model));

    expect(workflow.path).toBe(GITHUB_ACTIONS_WORKFLOW_PATH);
    expect(workflow.contents)
      .toBe(`# Generated by Architect Companion. Edit .architect-companion/ instead.
name: Architecture
on:
  pull_request: {}
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  architecture:
    name: Architecture checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Verify generated architecture targets
        run: npx --no-install architect-companion render --check
      - name: Run dependency-cruiser architecture checks
        run: npx --no-install depcruise --config .dependency-cruiser.cjs src/modules/billing src/modules/identity
`);
  });

  it("renders without an external engine step when no policy selects one", async () => {
    const model = await loadEffectiveHarnessModel({
      profilesDir,
      projectDir: sampleProjectDir,
    });

    const workflow = renderGitHubActionsWorkflow({ ...model, policies: [] });

    expect(workflow.contents).toContain("run: npx --no-install architect-companion render --check");
    expect(workflow.contents).not.toContain("depcruise");
  });

  it("omits dependency-cruiser when that target is not selected", async () => {
    const model = await loadEffectiveHarnessModel({
      profilesDir,
      projectDir: sampleProjectDir,
    });

    const workflow = renderGitHubActionsWorkflow({
      ...model,
      targets: {
        ...model.targets,
        dependencyCruiser: false,
      },
    });

    expect(workflow.contents).toContain("run: npx --no-install architect-companion render --check");
    expect(workflow.contents).not.toContain("depcruise");
  });
});

function withDependencyCruiserEnabled(
  model: Awaited<ReturnType<typeof loadEffectiveHarnessModel>>,
): Awaited<ReturnType<typeof loadEffectiveHarnessModel>> {
  return {
    ...model,
    targets: {
      ...model.targets,
      dependencyCruiser: true,
    },
  };
}
