import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { parseDocument, stringify } from "yaml";

import { findSymlinkedSegment } from "../io/path-safety.js";
import type { EffectiveHarnessModel } from "./effective-model.js";

export const PROFILE_LOCK_FILE_PATH = ".architect-companion/profile.lock.yml";

const GENERATED_HEADER =
  "# Generated by Architect Companion. Run `architect-companion upgrade-profile` to update.";

export type LockedProfile = {
  contentHash: string;
  name: string;
  version: string;
};

export type ProfileLock = {
  profiles: LockedProfile[];
  schemaVersion: 1;
};

export type ProfileLockStatus =
  | {
      expected: ProfileLock;
      kind: "match";
      lock: ProfileLock;
    }
  | {
      expected: ProfileLock;
      kind: "missing";
    }
  | {
      expected: ProfileLock;
      kind: "stale";
      lock: ProfileLock;
      reason: ProfileLockStaleReason;
    };

export type ProfileLockStaleReason =
  | "different-content-hash"
  | "different-profile-selection"
  | "different-version";

export class ProfileLockError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "ProfileLockError";
  }
}

export type ResolveProfileLockOptions = {
  model: EffectiveHarnessModel;
  profilesDir: string;
  projectDir: string;
};

export async function resolveProfileLockStatus(
  options: ResolveProfileLockOptions,
): Promise<ProfileLockStatus> {
  const expected = await computeExpectedProfileLock(options);
  const existing = await readProfileLock(options.projectDir);

  if (existing === undefined) {
    return { expected, kind: "missing" };
  }

  if (!sameProfileSelection(existing.profiles, expected.profiles)) {
    return { expected, kind: "stale", lock: existing, reason: "different-profile-selection" };
  }

  if (!sameProfileVersions(existing.profiles, expected.profiles)) {
    return { expected, kind: "stale", lock: existing, reason: "different-version" };
  }

  if (!sameProfileContentHashes(existing.profiles, expected.profiles)) {
    return { expected, kind: "stale", lock: existing, reason: "different-content-hash" };
  }

  return { expected, kind: "match", lock: existing };
}

export async function writeProfileLock(projectDir: string, lock: ProfileLock): Promise<void> {
  const absolutePath = path.join(projectDir, PROFILE_LOCK_FILE_PATH);
  await assertNoSymlinkedLockPath(projectDir, absolutePath);
  await writeFile(absolutePath, formatProfileLock(lock), "utf8");
}

export function formatProfileLock(lock: ProfileLock): string {
  return `${GENERATED_HEADER}\n${stringify(lock, { lineWidth: 0 })}`;
}

export function describeProfileLockStaleReason(
  status: Extract<ProfileLockStatus, { kind: "stale" }>,
): string {
  switch (status.reason) {
    case "different-profile-selection":
      return `selected profiles ${formatProfileList(status.expected.profiles)} do not match locked profiles ${formatProfileList(status.lock.profiles)}`;
    case "different-version":
      return `locked profile versions ${formatProfileList(status.lock.profiles)} do not match resolved versions ${formatProfileList(status.expected.profiles)}`;
    case "different-content-hash":
      return `profile content has changed since the lock was written for ${formatProfileList(status.expected.profiles)}`;
  }
}

async function computeExpectedProfileLock(
  options: ResolveProfileLockOptions,
): Promise<ProfileLock> {
  const profiles = await Promise.all(
    options.model.profiles.map(async (profile): Promise<LockedProfile> => {
      const profilePath = path.join(options.profilesDir, profile.name, "profile.yml");
      const bytes = await readFile(profilePath);
      const contentHash = `sha256-${createHash("sha256").update(bytes).digest("hex")}`;

      return {
        contentHash,
        name: profile.name,
        version: profile.version,
      };
    }),
  );

  return {
    profiles,
    schemaVersion: 1,
  };
}

async function readProfileLock(projectDir: string): Promise<ProfileLock | undefined> {
  const lockPath = path.join(projectDir, PROFILE_LOCK_FILE_PATH);
  await assertNoSymlinkedLockPath(projectDir, lockPath);
  let source: string;
  try {
    source = await readFile(lockPath, "utf8");
  } catch (error: unknown) {
    if (isNodeError(error) && error.code === "ENOENT") {
      return undefined;
    }
    throw error;
  }

  const document = parseDocument(source);
  if (document.errors.length > 0) {
    const firstError = document.errors[0];
    throw new ProfileLockError(
      `${PROFILE_LOCK_FILE_PATH}: invalid YAML${firstError?.message === undefined ? "." : `: ${firstError.message}`}`,
    );
  }

  return parseProfileLock(document.toJS());
}

function parseProfileLock(value: unknown): ProfileLock {
  const root = asObject(value, "$");
  if (root.schemaVersion !== 1) {
    throw new ProfileLockError(`${PROFILE_LOCK_FILE_PATH}: schemaVersion must be 1.`);
  }

  if (!Array.isArray(root.profiles)) {
    throw new ProfileLockError(`${PROFILE_LOCK_FILE_PATH}: profiles must be an array.`);
  }

  if (root.profiles.length === 0) {
    throw new ProfileLockError(
      `${PROFILE_LOCK_FILE_PATH}: profiles must include at least one item.`,
    );
  }

  const names = new Set<string>();
  const profiles = root.profiles.map((profileValue, index): LockedProfile => {
    const fieldPath = `profiles[${index}]`;
    const profileRoot = asObject(profileValue, fieldPath);
    const name = asNonEmptyString(profileRoot.name, `${fieldPath}.name`);

    if (names.has(name)) {
      throw new ProfileLockError(
        `${PROFILE_LOCK_FILE_PATH}: ${fieldPath}.name duplicates profile "${name}".`,
      );
    }
    names.add(name);

    return {
      contentHash: asNonEmptyString(profileRoot.contentHash, `${fieldPath}.contentHash`),
      name,
      version: asNonEmptyString(profileRoot.version, `${fieldPath}.version`),
    };
  });

  return {
    profiles,
    schemaVersion: 1,
  };
}

function sameProfileSelection(left: LockedProfile[], right: LockedProfile[]): boolean {
  return sameProfileValues(left, right, (profile) => profile.name);
}

function sameProfileVersions(left: LockedProfile[], right: LockedProfile[]): boolean {
  return sameProfileValues(left, right, (profile) => profile.version);
}

function sameProfileContentHashes(left: LockedProfile[], right: LockedProfile[]): boolean {
  return sameProfileValues(left, right, (profile) => profile.contentHash);
}

function sameProfileValues(
  left: LockedProfile[],
  right: LockedProfile[],
  selectValue: (profile: LockedProfile) => string,
): boolean {
  if (left.length !== right.length) {
    return false;
  }

  return left.every((profile, index) => {
    const other = right[index];
    return other !== undefined && selectValue(profile) === selectValue(other);
  });
}

function formatProfileList(profiles: LockedProfile[]): string {
  return profiles.map((profile) => `"${profile.name}@${profile.version}"`).join(", ");
}

function asObject(value: unknown, fieldPath: string): Record<string, unknown> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    throw new ProfileLockError(`${PROFILE_LOCK_FILE_PATH}: ${fieldPath} must be an object.`);
  }

  return value as Record<string, unknown>;
}

function asNonEmptyString(value: unknown, fieldPath: string): string {
  if (typeof value !== "string" || value.trim() === "") {
    throw new ProfileLockError(
      `${PROFILE_LOCK_FILE_PATH}: ${fieldPath} must be a non-empty string.`,
    );
  }

  return value;
}

function isNodeError(error: unknown): error is NodeJS.ErrnoException {
  return typeof error === "object" && error !== null && "code" in error;
}

async function assertNoSymlinkedLockPath(projectDir: string, lockPath: string): Promise<void> {
  const symlinked = await findSymlinkedSegment(projectDir, lockPath);
  if (symlinked !== undefined) {
    throw new ProfileLockError(
      `${PROFILE_LOCK_FILE_PATH}: lock path contains a symbolic link; refusing to read or write the profile lock through symlinks. Remove the symlink and re-run \`architect-companion render\` or \`architect-companion upgrade-profile\`.`,
    );
  }
}
