import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { parseDocument, stringify } from "yaml";

import { findSymlinkedSegment } from "../io/path-safety.js";
import type { EffectiveHarnessModel } from "./effective-model.js";

export const PROFILE_LOCK_FILE_PATH = ".architect-companion/profile.lock.yml";

const GENERATED_HEADER =
  "# Generated by Architect Companion. Run `architect-companion upgrade-profile` to update.";

export type ProfileLock = {
  profile: {
    contentHash: string;
    name: string;
    version: string;
  };
  schemaVersion: 1;
};

export type ProfileLockStatus =
  | {
      expected: ProfileLock;
      kind: "match";
      lock: ProfileLock;
    }
  | {
      expected: ProfileLock;
      kind: "missing";
    }
  | {
      expected: ProfileLock;
      kind: "stale";
      lock: ProfileLock;
      reason: ProfileLockStaleReason;
    };

export type ProfileLockStaleReason =
  | "different-name"
  | "different-version"
  | "different-content-hash";

export class ProfileLockError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "ProfileLockError";
  }
}

type ResolveProfileLockOptions = {
  model: EffectiveHarnessModel;
  profilesDir: string;
  projectDir: string;
};

export async function resolveProfileLockStatus(
  options: ResolveProfileLockOptions,
): Promise<ProfileLockStatus> {
  const expected = await computeExpectedProfileLock(options);
  const existing = await readProfileLock(options.projectDir);

  if (existing === undefined) {
    return { expected, kind: "missing" };
  }

  if (existing.profile.name !== expected.profile.name) {
    return { expected, kind: "stale", lock: existing, reason: "different-name" };
  }

  if (existing.profile.version !== expected.profile.version) {
    return { expected, kind: "stale", lock: existing, reason: "different-version" };
  }

  if (existing.profile.contentHash !== expected.profile.contentHash) {
    return { expected, kind: "stale", lock: existing, reason: "different-content-hash" };
  }

  return { expected, kind: "match", lock: existing };
}

export async function writeProfileLock(projectDir: string, lock: ProfileLock): Promise<void> {
  const absolutePath = path.join(projectDir, PROFILE_LOCK_FILE_PATH);
  await assertNoSymlinkedLockPath(projectDir, absolutePath);
  await writeFile(absolutePath, formatProfileLock(lock), "utf8");
}

export function formatProfileLock(lock: ProfileLock): string {
  return `${GENERATED_HEADER}\n${stringify(lock, { lineWidth: 0 })}`;
}

export function describeProfileLockStaleReason(
  status: Extract<ProfileLockStatus, { kind: "stale" }>,
): string {
  switch (status.reason) {
    case "different-name":
      return `selected profile "${status.expected.profile.name}" does not match locked profile "${status.lock.profile.name}"`;
    case "different-version":
      return `locked profile version ${status.lock.profile.version} does not match resolved version ${status.expected.profile.version}`;
    case "different-content-hash":
      return `profile "${status.expected.profile.name}@${status.expected.profile.version}" content has changed since the lock was written`;
  }
}

async function computeExpectedProfileLock(
  options: ResolveProfileLockOptions,
): Promise<ProfileLock> {
  const profilePath = path.join(options.profilesDir, options.model.profile.name, "profile.yml");
  const bytes = await readFile(profilePath);
  const contentHash = `sha256-${createHash("sha256").update(bytes).digest("hex")}`;

  return {
    profile: {
      contentHash,
      name: options.model.profile.name,
      version: options.model.profile.version,
    },
    schemaVersion: 1,
  };
}

async function readProfileLock(projectDir: string): Promise<ProfileLock | undefined> {
  const lockPath = path.join(projectDir, PROFILE_LOCK_FILE_PATH);
  await assertNoSymlinkedLockPath(projectDir, lockPath);
  let source: string;
  try {
    source = await readFile(lockPath, "utf8");
  } catch (error: unknown) {
    if (isNodeError(error) && error.code === "ENOENT") {
      return undefined;
    }
    throw error;
  }

  const document = parseDocument(source);
  if (document.errors.length > 0) {
    const firstError = document.errors[0];
    throw new ProfileLockError(
      `${PROFILE_LOCK_FILE_PATH}: invalid YAML${firstError?.message === undefined ? "." : `: ${firstError.message}`}`,
    );
  }

  return parseProfileLock(document.toJS());
}

function parseProfileLock(value: unknown): ProfileLock {
  const root = asObject(value, "$");
  if (root.schemaVersion !== 1) {
    throw new ProfileLockError(`${PROFILE_LOCK_FILE_PATH}: schemaVersion must be 1.`);
  }

  const profileRoot = asObject(root.profile, "profile");
  return {
    profile: {
      contentHash: asNonEmptyString(profileRoot.contentHash, "profile.contentHash"),
      name: asNonEmptyString(profileRoot.name, "profile.name"),
      version: asNonEmptyString(profileRoot.version, "profile.version"),
    },
    schemaVersion: 1,
  };
}

function asObject(value: unknown, fieldPath: string): Record<string, unknown> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    throw new ProfileLockError(`${PROFILE_LOCK_FILE_PATH}: ${fieldPath} must be an object.`);
  }

  return value as Record<string, unknown>;
}

function asNonEmptyString(value: unknown, fieldPath: string): string {
  if (typeof value !== "string" || value.trim() === "") {
    throw new ProfileLockError(
      `${PROFILE_LOCK_FILE_PATH}: ${fieldPath} must be a non-empty string.`,
    );
  }

  return value;
}

function isNodeError(error: unknown): error is NodeJS.ErrnoException {
  return typeof error === "object" && error !== null && "code" in error;
}

async function assertNoSymlinkedLockPath(projectDir: string, lockPath: string): Promise<void> {
  const symlinked = await findSymlinkedSegment(projectDir, lockPath);
  if (symlinked !== undefined) {
    throw new ProfileLockError(
      `${PROFILE_LOCK_FILE_PATH}: lock path contains a symbolic link; refusing to read or write the profile lock through symlinks. Remove the symlink and re-run \`architect-companion render\` or \`architect-companion upgrade-profile\`.`,
    );
  }
}
