import { lstat, mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

import type { EffectiveHarnessModel, KnownTargetKey } from "../model/effective-model.js";
import { knownTargetKeys } from "../model/effective-model.js";

export const GENERATED_FILE_MARKER =
  "Generated by Architect Companion. Edit .architect-companion/ instead.";

const markdownGeneratedHeader = `<!-- ${GENERATED_FILE_MARKER} -->`;
const supportedRenderers = [createAgentsMdRenderer(), createCursorRenderer()] satisfies Renderer[];

type RenderStatus = "created" | "stale" | "unchanged" | "updated";

export type Renderer = {
  outputPath: string;
  render(model: EffectiveHarnessModel): string;
  target: KnownTargetKey;
};

export type RenderResult = {
  outputPath: string;
  reason?: "content differs" | "missing";
  status: RenderStatus;
  target: KnownTargetKey;
};

export type RenderOptions = {
  check?: boolean;
  model: EffectiveHarnessModel;
  projectDir: string;
};

export class RenderError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "RenderError";
  }
}

export async function renderEffectiveHarnessModel(options: RenderOptions): Promise<RenderResult[]> {
  const projectDir = path.resolve(options.projectDir);
  const selectedRenderers = getSelectedRenderers(options.model);
  const results: RenderResult[] = [];

  for (const renderer of selectedRenderers) {
    const outputPath = renderer.outputPath;
    const absoluteOutputPath = resolveOutputPath(projectDir, outputPath);
    const content = ensureTrailingNewline(renderer.render(options.model));

    if (!hasGeneratedMarker(content)) {
      throw new RenderError(`${outputPath}: renderer output is missing the generated-file marker.`);
    }

    await assertNoSymlinkedOutputPath(projectDir, absoluteOutputPath, outputPath);

    const existingContent = await readOptionalFile(absoluteOutputPath);

    if (existingContent === undefined) {
      if (options.check === true) {
        results.push({
          outputPath,
          reason: "missing",
          status: "stale",
          target: renderer.target,
        });
        continue;
      }

      await mkdir(path.dirname(absoluteOutputPath), { recursive: true });
      await writeFile(absoluteOutputPath, content, "utf8");
      results.push({ outputPath, status: "created", target: renderer.target });
      continue;
    }

    if (existingContent === content) {
      results.push({ outputPath, status: "unchanged", target: renderer.target });
      continue;
    }

    if (!hasGeneratedMarker(existingContent)) {
      throw new RenderError(
        `${outputPath}: existing file is not marked as generated by Architect Companion; refusing to overwrite.`,
      );
    }

    if (options.check === true) {
      results.push({
        outputPath,
        reason: "content differs",
        status: "stale",
        target: renderer.target,
      });
      continue;
    }

    await writeFile(absoluteOutputPath, content, "utf8");
    results.push({ outputPath, status: "updated", target: renderer.target });
  }

  return results;
}

function getSelectedRenderers(model: EffectiveHarnessModel): Renderer[] {
  const renderersByTarget = new Map(
    supportedRenderers.map((renderer) => [renderer.target, renderer]),
  );
  const unsupportedTargets = knownTargetKeys.filter(
    (target) => model.targets[target] && !renderersByTarget.has(target),
  );

  if (unsupportedTargets.length > 0) {
    throw new RenderError(
      `Selected target${unsupportedTargets.length === 1 ? "" : "s"} ${unsupportedTargets.join(
        ", ",
      )} ${unsupportedTargets.length === 1 ? "does" : "do"} not have a renderer yet.`,
    );
  }

  return knownTargetKeys
    .map((target) => renderersByTarget.get(target))
    .filter(
      (renderer): renderer is Renderer => renderer !== undefined && model.targets[renderer.target],
    );
}

function createAgentsMdRenderer(): Renderer {
  return {
    outputPath: "AGENTS.md",
    render(model) {
      return `${markdownGeneratedHeader}

# Agent Instructions

${renderGuidanceBody(model)}`;
    },
    target: "agentsMd",
  };
}

function createCursorRenderer(): Renderer {
  return {
    outputPath: ".cursor/rules/architect-companion.mdc",
    render(model) {
      return `---
description: Generated architecture guidance from Architect Companion
alwaysApply: true
---
${markdownGeneratedHeader}

# Architect Companion Guidance

${renderGuidanceBody(model)}`;
    },
    target: "cursor",
  };
}

function renderGuidanceBody(model: EffectiveHarnessModel): string {
  const profileTitle = model.profile.title ?? model.profile.name;
  const lines: string[] = [
    `Project: ${model.project.name}`,
    `Profile: ${profileTitle} (${model.profile.name} ${model.profile.version})`,
    `Stack: ${model.stack}`,
    "",
  ];

  appendPrinciples(lines, model);
  appendPolicies(lines, model);
  appendModules(lines, model);
  appendWorkflows(lines, model);
  appendHeuristics(lines, model);
  appendExamples(lines, model);

  return lines.join("\n");
}

function appendPrinciples(lines: string[], model: EffectiveHarnessModel): void {
  if (model.principles.length === 0) {
    return;
  }

  lines.push("## Principles");
  lines.push("");
  for (const principle of model.principles) {
    lines.push(`- ${principle.title}: ${principle.guidance}`);
  }
  lines.push("");
}

function appendPolicies(lines: string[], model: EffectiveHarnessModel): void {
  if (model.policies.length === 0) {
    return;
  }

  lines.push("## Policies");
  lines.push("");
  for (const policy of model.policies) {
    lines.push(`### ${policy.title}`);
    lines.push("");
    lines.push(`Severity: ${policy.severity}`);
    lines.push("");
    lines.push(`Intent: ${policy.intent}`);
    lines.push("");
    lines.push(policy.guidance);
    lines.push("");
  }
}

function appendModules(lines: string[], model: EffectiveHarnessModel): void {
  if (model.modules.length === 0) {
    return;
  }

  lines.push("## Modules");
  lines.push("");
  for (const module of model.modules) {
    lines.push(`- ${module.name}: ${module.path}`);
    lines.push(`  Public API: ${module.publicApi}`);
    lines.push(
      `  Allowed dependencies: ${(model.allowedDependencies[module.name] ?? []).join(", ") || "none"}`,
    );
  }
  lines.push("");
}

function appendWorkflows(lines: string[], model: EffectiveHarnessModel): void {
  if (model.workflows.length === 0) {
    return;
  }

  lines.push("## Workflows");
  lines.push("");
  for (const workflow of model.workflows) {
    lines.push(`### ${workflow.title}`);
    lines.push("");
    workflow.steps.forEach((step, index) => {
      lines.push(`${index + 1}. ${step}`);
    });
    lines.push("");
  }
}

function appendHeuristics(lines: string[], model: EffectiveHarnessModel): void {
  if (model.heuristics.length === 0) {
    return;
  }

  lines.push("## Review Heuristics");
  lines.push("");
  for (const heuristic of model.heuristics) {
    lines.push(`### ${heuristic.title}`);
    lines.push("");
    for (const question of heuristic.questions) {
      lines.push(`- ${question}`);
    }
    lines.push("");
  }
}

function appendExamples(lines: string[], model: EffectiveHarnessModel): void {
  if (model.examples.length === 0) {
    return;
  }

  lines.push("## Examples");
  lines.push("");
  for (const example of model.examples) {
    lines.push(`### ${example.title}`);
    lines.push("");
    lines.push("Good:");
    lines.push("");
    lines.push("```ts");
    lines.push(example.good);
    lines.push("```");
    lines.push("");
    lines.push("Bad:");
    lines.push("");
    lines.push("```ts");
    lines.push(example.bad);
    lines.push("```");
    lines.push("");
  }
}

async function readOptionalFile(filePath: string): Promise<string | undefined> {
  try {
    return await readFile(filePath, "utf8");
  } catch (error: unknown) {
    if (isNodeError(error) && error.code === "ENOENT") {
      return undefined;
    }

    throw error;
  }
}

async function assertNoSymlinkedOutputPath(
  projectDir: string,
  absoluteOutputPath: string,
  outputPath: string,
): Promise<void> {
  const relativePath = path.relative(projectDir, absoluteOutputPath);
  const segments = relativePath.split(path.sep).filter((segment) => segment.length > 0);
  let currentPath = projectDir;

  for (const segment of segments) {
    currentPath = path.join(currentPath, segment);
    const stats = await lstatOptional(currentPath);

    if (stats === undefined) {
      return;
    }

    if (stats.isSymbolicLink()) {
      throw new RenderError(
        `${outputPath}: output path contains a symbolic link; refusing to write generated files through symlinks.`,
      );
    }
  }
}

async function lstatOptional(
  filePath: string,
): Promise<Awaited<ReturnType<typeof lstat>> | undefined> {
  try {
    return await lstat(filePath);
  } catch (error: unknown) {
    if (isNodeError(error) && error.code === "ENOENT") {
      return undefined;
    }

    throw error;
  }
}

function resolveOutputPath(projectDir: string, outputPath: string): string {
  const absolutePath = path.resolve(projectDir, outputPath);
  const relativePath = path.relative(projectDir, absolutePath);

  if (relativePath.startsWith("..") || path.isAbsolute(relativePath)) {
    throw new RenderError(`${outputPath}: rendered file path escapes the project directory.`);
  }

  return absolutePath;
}

function ensureTrailingNewline(value: string): string {
  return value.endsWith("\n") ? value : `${value}\n`;
}

function hasGeneratedMarker(source: string): boolean {
  return source.split(/\r?\n/, 8).some((line) => line.includes(GENERATED_FILE_MARKER));
}

function isNodeError(error: unknown): error is NodeJS.ErrnoException {
  return error instanceof Error && "code" in error;
}
