import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

import { renderDependencyCruiserConfig } from "../integrations/dependency-cruiser.js";
import { findSymlinkedSegment } from "../io/path-safety.js";
import type { EffectiveHarnessModel, KnownTargetKey } from "../model/effective-model.js";
import {
  renderAgentsMd,
  renderClaudeMd,
  renderCursorRules,
} from "../renderers/agent-instructions.js";
import {
  claudeHookScriptPaths,
  CLAUDE_SETTINGS_PATH,
  renderClaudeHooksTarget,
} from "../renderers/claude-hooks.js";
import { renderGitHubActionsWorkflow } from "../renderers/github-actions.js";
import { renderPrAgentTarget } from "../renderers/pr-agent.js";
import { getTargetMetadata, knownTargetKeys } from "../targets/target-registry.js";
import { GENERATED_FILE_MARKER } from "./generated-file.js";

export { GENERATED_FILE_MARKER } from "./generated-file.js";

const targetRenderers = [
  createTargetRenderer("agentsMd", renderAgentsMd),
  createTargetRenderer("claudeMd", renderClaudeMd),
  createTargetRenderer("cursor", renderCursorRules),
  createTargetRenderer("dependencyCruiser", renderDependencyCruiserConfig),
  createTargetRenderer("githubActions", (model) => renderGitHubActionsWorkflow(model).contents),
  { render: (model) => renderPrAgentTarget(model), target: "prAgent" },
  { render: (model) => renderClaudeHooksTarget(model), target: "claudeHooks" },
] satisfies TargetRenderer[];

assertEveryKnownTargetHasRenderer(targetRenderers);
assertClaudeHooksOutputsMatchCatalog();

type RenderStatus = "created" | "stale" | "unchanged" | "updated";

type TargetRenderer = {
  render(model: EffectiveHarnessModel): readonly string[];
  target: KnownTargetKey;
};

type RenderedTargetOutput = {
  content: string;
  outputPath: string;
  target: KnownTargetKey;
};

export type RenderResult = {
  outputPath: string;
  reason?: "content differs" | "missing";
  status: RenderStatus;
  target: KnownTargetKey;
};

export type RenderOptions = {
  check?: boolean;
  model: EffectiveHarnessModel;
  projectDir: string;
};

export class RenderError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "RenderError";
  }
}

export type RendererOutput = {
  outputPath: string;
  target: KnownTargetKey;
};

export function getRendererOutputs(
  targets: Partial<Record<KnownTargetKey, boolean>>,
): RendererOutput[] {
  return knownTargetKeys.flatMap((target) => {
    if (targets[target] !== true) {
      return [];
    }
    return getTargetMetadata(target).outputs.map((output) => ({
      outputPath: output.outputPath,
      target,
    }));
  });
}

export async function renderEffectiveHarnessModel(options: RenderOptions): Promise<RenderResult[]> {
  const projectDir = path.resolve(options.projectDir);
  const selectedOutputs = getSelectedTargetOutputs(options.model);
  const results: RenderResult[] = [];

  for (const output of selectedOutputs) {
    const outputPath = output.outputPath;
    const absoluteOutputPath = resolveOutputPath(projectDir, outputPath);
    const content = ensureTrailingNewline(output.content);

    if (!hasGeneratedMarker(content)) {
      throw new RenderError(`${outputPath}: renderer output is missing the generated-file marker.`);
    }

    await assertNoSymlinkedOutputPath(projectDir, absoluteOutputPath, outputPath);

    const existingContent = await readOptionalFile(absoluteOutputPath);

    if (existingContent === undefined) {
      if (options.check === true) {
        results.push({
          outputPath,
          reason: "missing",
          status: "stale",
          target: output.target,
        });
        continue;
      }

      await mkdir(path.dirname(absoluteOutputPath), { recursive: true });
      await writeFile(absoluteOutputPath, content, "utf8");
      results.push({ outputPath, status: "created", target: output.target });
      continue;
    }

    if (existingContent === content) {
      results.push({ outputPath, status: "unchanged", target: output.target });
      continue;
    }

    if (!hasGeneratedMarker(existingContent)) {
      throw new RenderError(
        `${outputPath}: existing file is not marked as generated by Architect Companion; refusing to overwrite. Move or delete the existing file, or add the generated-file marker line "${GENERATED_FILE_MARKER}" if Architect Companion should manage it.`,
      );
    }

    if (options.check === true) {
      results.push({
        outputPath,
        reason: "content differs",
        status: "stale",
        target: output.target,
      });
      continue;
    }

    await writeFile(absoluteOutputPath, content, "utf8");
    results.push({ outputPath, status: "updated", target: output.target });
  }

  return results;
}

function getSelectedTargetOutputs(model: EffectiveHarnessModel): RenderedTargetOutput[] {
  const renderersByTarget = new Map(targetRenderers.map((renderer) => [renderer.target, renderer]));

  return knownTargetKeys.flatMap((target) => {
    if (!model.targets[target]) {
      return [];
    }

    const renderer = renderersByTarget.get(target);
    if (renderer === undefined) {
      return [];
    }

    return renderTargetOutputs(renderer, model);
  });
}

function createTargetRenderer(
  target: KnownTargetKey,
  render: (model: EffectiveHarnessModel) => string,
): TargetRenderer {
  return {
    render(model) {
      return [render(model)];
    },
    target,
  };
}

function assertEveryKnownTargetHasRenderer(renderers: readonly TargetRenderer[]): void {
  const registered = new Set(renderers.map((renderer) => renderer.target));
  const missing = knownTargetKeys.filter((target) => !registered.has(target));
  if (missing.length > 0) {
    throw new Error(
      `Architect Companion bug: no renderer registered for target(s) ${missing.join(", ")}. The target registry and render.ts are out of sync.`,
    );
  }
}

/**
 * The Claude hooks catalog drives the rendered scripts, but the target registry
 * is the static source of truth for output paths (used by `--check`, init
 * pre-flight, and conflict detection). The `targets` boundary cannot import the
 * renderer catalog, so this guards the two against drift: adding a hook means
 * appending a catalog entry and its registry output, and this fails loudly if
 * they fall out of sync.
 */
function assertClaudeHooksOutputsMatchCatalog(): void {
  const declared = getTargetMetadata("claudeHooks").outputs.map((output) => output.outputPath);
  const expected = [CLAUDE_SETTINGS_PATH, ...claudeHookScriptPaths()];
  const inSync =
    declared.length === expected.length &&
    declared.every((outputPath, index) => outputPath === expected[index]);
  if (!inSync) {
    throw new Error(
      `Architect Companion bug: claudeHooks registry outputs ${JSON.stringify(declared)} are out of sync with the hook catalog ${JSON.stringify(expected)}. Update src/targets/target-registry.ts to match the catalog in src/renderers/claude-hooks.ts.`,
    );
  }
}

function renderTargetOutputs(
  renderer: TargetRenderer,
  model: EffectiveHarnessModel,
): RenderedTargetOutput[] {
  const metadata = getTargetMetadata(renderer.target);
  const contents = renderer.render(model);

  if (contents.length !== metadata.outputs.length) {
    throw new RenderError(
      `${renderer.target}: renderer produced ${contents.length} output(s), but the target registry declares ${metadata.outputs.length}.`,
    );
  }

  return metadata.outputs.map((output, index) => ({
    content: contents[index] ?? "",
    outputPath: output.outputPath,
    target: renderer.target,
  }));
}

async function readOptionalFile(filePath: string): Promise<string | undefined> {
  try {
    return await readFile(filePath, "utf8");
  } catch (error: unknown) {
    if (isNodeError(error) && error.code === "ENOENT") {
      return undefined;
    }

    throw error;
  }
}

async function assertNoSymlinkedOutputPath(
  projectDir: string,
  absoluteOutputPath: string,
  outputPath: string,
): Promise<void> {
  const symlinked = await findSymlinkedSegment(projectDir, absoluteOutputPath);
  if (symlinked !== undefined) {
    throw new RenderError(
      `${outputPath}: output path contains a symbolic link; refusing to write generated files through symlinks. Remove the symlink and re-run \`architect-companion render\`.`,
    );
  }
}

function resolveOutputPath(projectDir: string, outputPath: string): string {
  const absolutePath = path.resolve(projectDir, outputPath);
  const relativePath = path.relative(projectDir, absolutePath);

  if (relativePath.startsWith("..") || path.isAbsolute(relativePath)) {
    throw new RenderError(`${outputPath}: rendered file path escapes the project directory.`);
  }

  return absolutePath;
}

function ensureTrailingNewline(value: string): string {
  return value.endsWith("\n") ? value : `${value}\n`;
}

function hasGeneratedMarker(source: string): boolean {
  return source.split(/\r?\n/, 8).some((line) => line.includes(GENERATED_FILE_MARKER));
}

function isNodeError(error: unknown): error is NodeJS.ErrnoException {
  return error instanceof Error && "code" in error;
}
