import type { EffectiveHarnessModel } from "../model/effective-model.js";

export const DEPENDENCY_CRUISER_TARGET_FILE = ".dependency-cruiser.cjs";

const dependencyCruiserEngine = "dependency-cruiser";
const dependencyCruiserRenderer = "dependency-cruiser-config";
const moduleBoundariesPolicyId = "module-boundaries";

type DependencyCruiserSeverity = "error" | "info" | "warn";
type NormalizedViolationSeverity = "advisory" | "error" | "warning";

export type DependencyCruiserForbiddenRule = {
  comment: string;
  from: {
    path: string;
  };
  name: string;
  severity: DependencyCruiserSeverity;
  to: {
    path: string;
  };
};

export type DependencyCruiserConfig = {
  forbidden: DependencyCruiserForbiddenRule[];
  options: {
    combinedDependencies: boolean;
    doNotFollow: {
      path: string[];
    };
    enhancedResolveOptions: {
      conditionNames: string[];
      exportsFields: string[];
      extensions: string[];
    };
    tsPreCompilationDeps: boolean;
  };
};

export type DependencyCruiserPolicyImplementationContract = {
  engine: typeof dependencyCruiserEngine;
  policyId: typeof moduleBoundariesPolicyId;
  renderer: typeof dependencyCruiserRenderer;
  stack: "typescript";
};

export type DependencyCruiserCommandMetadata = {
  args: string[];
  configFile: typeof DEPENDENCY_CRUISER_TARGET_FILE;
  engine: typeof dependencyCruiserEngine;
  executable: "depcruise";
  inputPaths: string[];
  outputType: "json";
  resultMapper: "dependency-cruiser-json";
};

export type DependencyCruiserResult = {
  engine: typeof dependencyCruiserEngine;
  ok: boolean;
  summary: {
    advisory: number;
    error: number;
    totalCruised: number;
    totalDependenciesCruised?: number;
    warning: number;
  };
  violations: DependencyCruiserViolation[];
};

export type DependencyCruiserViolation = {
  engine: typeof dependencyCruiserEngine;
  from: string;
  message: string;
  policyId?: string;
  rawSeverity: string;
  ruleName: string;
  severity: NormalizedViolationSeverity;
  to: string;
};

export class DependencyCruiserIntegrationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "DependencyCruiserIntegrationError";
  }
}

export const dependencyCruiserPolicyImplementationContract: DependencyCruiserPolicyImplementationContract =
  {
    engine: dependencyCruiserEngine,
    policyId: moduleBoundariesPolicyId,
    renderer: dependencyCruiserRenderer,
    stack: "typescript",
  };

export function createDependencyCruiserConfig(
  model: EffectiveHarnessModel,
): DependencyCruiserConfig {
  const policy = getModuleBoundariesPolicy(model);
  const modules = [...model.modules].sort((left, right) => left.name.localeCompare(right.name));
  const severity = toDependencyCruiserSeverity(policy.severity);
  const forbidden = modules.flatMap((sourceModule) => {
    const allowedDependencies = new Set(model.allowedDependencies[sourceModule.name] ?? []);

    return modules.flatMap((targetModule): DependencyCruiserForbiddenRule[] => {
      if (sourceModule.name === targetModule.name) {
        return [];
      }

      assertPublicApiWithinModule(targetModule);

      if (!allowedDependencies.has(targetModule.name)) {
        return [
          {
            comment: `${sourceModule.name} does not declare ${targetModule.name} as an allowed module dependency.`,
            from: {
              path: modulePathPattern(sourceModule.path),
            },
            name: ruleName(sourceModule.name, targetModule.name, "undeclared-dependency"),
            severity,
            to: {
              path: modulePathPattern(targetModule.path),
            },
          },
        ];
      }

      return [
        {
          comment: `${sourceModule.name} may depend on ${targetModule.name} only through ${targetModule.publicApi}.`,
          from: {
            path: modulePathPattern(sourceModule.path),
          },
          name: ruleName(sourceModule.name, targetModule.name, "internal-import"),
          severity,
          to: {
            path: moduleInternalPathPattern(targetModule.path, targetModule.publicApi),
          },
        },
      ];
    });
  });

  return {
    forbidden,
    options: {
      combinedDependencies: true,
      doNotFollow: {
        path: ["node_modules"],
      },
      enhancedResolveOptions: {
        conditionNames: ["import", "require", "node", "default", "types"],
        exportsFields: ["exports"],
        extensions: [".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs", ".json"],
      },
      tsPreCompilationDeps: true,
    },
  };
}

export function renderDependencyCruiserConfig(model: EffectiveHarnessModel): string {
  return [
    "// Generated by Architect Companion. Edit .architect-companion/ instead.",
    "/** @type {import('dependency-cruiser').IConfiguration} */",
    `module.exports = ${JSON.stringify(createDependencyCruiserConfig(model), null, 2)};`,
    "",
  ].join("\n");
}

export function getDependencyCruiserCommandMetadata(
  model: EffectiveHarnessModel,
): DependencyCruiserCommandMetadata {
  const inputPaths = Array.from(new Set(model.modules.map((module) => module.path))).sort(
    (left, right) => left.localeCompare(right),
  );

  return {
    args: ["--config", DEPENDENCY_CRUISER_TARGET_FILE, "--output-type", "json", ...inputPaths],
    configFile: DEPENDENCY_CRUISER_TARGET_FILE,
    engine: dependencyCruiserEngine,
    executable: "depcruise",
    inputPaths,
    outputType: "json",
    resultMapper: "dependency-cruiser-json",
  };
}

export function mapDependencyCruiserJsonResult(value: unknown): DependencyCruiserResult {
  const root = asObject(value, "$");
  const summaryRoot = asObject(root.summary, "summary");
  const violations = asArray(summaryRoot.violations, "summary.violations").map(
    (violation, index): DependencyCruiserViolation => {
      const violationPath = `summary.violations[${index}]`;
      const violationRoot = asObject(violation, violationPath);
      const ruleRoot = asObject(violationRoot.rule, `${violationPath}.rule`);
      const ruleNameValue = optionalString(ruleRoot.name) ?? "unnamed";
      const rawSeverity = optionalString(ruleRoot.severity) ?? "warn";
      const comment = optionalString(ruleRoot.comment);
      const from = asString(violationRoot.from, `${violationPath}.from`);
      const to = asString(violationRoot.to, `${violationPath}.to`);
      const policyId = policyIdFromRuleName(ruleNameValue);

      return {
        engine: dependencyCruiserEngine,
        from,
        message: comment ?? `${from} -> ${to} violates ${ruleNameValue}.`,
        ...(policyId === undefined ? {} : { policyId }),
        rawSeverity,
        ruleName: ruleNameValue,
        severity: toNormalizedViolationSeverity(rawSeverity),
        to,
      };
    },
  );

  const summary = {
    advisory: optionalNumber(summaryRoot.info) ?? 0,
    error: optionalNumber(summaryRoot.error) ?? 0,
    totalCruised: optionalNumber(summaryRoot.totalCruised) ?? 0,
    warning: optionalNumber(summaryRoot.warn) ?? 0,
  };
  const totalDependenciesCruised = optionalNumber(summaryRoot.totalDependenciesCruised);

  return {
    engine: dependencyCruiserEngine,
    ok: violations.length === 0,
    summary:
      totalDependenciesCruised === undefined
        ? summary
        : {
            ...summary,
            totalDependenciesCruised,
          },
    violations,
  };
}

function getModuleBoundariesPolicy(
  model: EffectiveHarnessModel,
): EffectiveHarnessModel["policies"][number] {
  const policy = model.policies.find((candidate) => candidate.id === moduleBoundariesPolicyId);
  const implementation = policy?.implementation?.[model.stack];

  if (
    policy === undefined ||
    implementation?.engine !== dependencyCruiserEngine ||
    implementation.renderer !== dependencyCruiserRenderer
  ) {
    throw new DependencyCruiserIntegrationError(
      `The ${moduleBoundariesPolicyId} policy must declare a ${dependencyCruiserEngine} implementation with the ${dependencyCruiserRenderer} renderer for ${model.stack}.`,
    );
  }

  return policy;
}

function toDependencyCruiserSeverity(
  severity: EffectiveHarnessModel["policies"][number]["severity"],
): DependencyCruiserSeverity {
  switch (severity) {
    case "advisory":
      return "info";
    case "error":
      return "error";
    case "warning":
      return "warn";
  }
}

function toNormalizedViolationSeverity(severity: string): NormalizedViolationSeverity {
  switch (severity) {
    case "error":
      return "error";
    case "info":
      return "advisory";
    case "warn":
      return "warning";
    default:
      return "warning";
  }
}

function assertPublicApiWithinModule(module: EffectiveHarnessModel["modules"][number]): void {
  if (!module.publicApi.startsWith(`${module.path}/`) && module.publicApi !== module.path) {
    throw new DependencyCruiserIntegrationError(
      `${module.name} public API "${module.publicApi}" must be inside module path "${module.path}" to generate dependency-cruiser rules.`,
    );
  }
}

function modulePathPattern(modulePath: string): string {
  return `^${escapeRegExp(modulePath)}(?:/|$)`;
}

function moduleInternalPathPattern(modulePath: string, publicApiPath: string): string {
  if (modulePath === publicApiPath) {
    return `^$`;
  }
  return `^(?!${escapeRegExp(publicApiPath)}$)${escapeRegExp(modulePath)}(?:/|$)`;
}

function ruleName(sourceModule: string, targetModule: string, ruleKind: string): string {
  return `architect-companion/${moduleBoundariesPolicyId}/${sourceModule}-to-${targetModule}/${ruleKind}`;
}

function policyIdFromRuleName(ruleNameValue: string): string | undefined {
  return /^architect-companion\/([^/]+)\//.exec(ruleNameValue)?.[1];
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function asObject(value: unknown, fieldPath: string): Record<string, unknown> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    throw new DependencyCruiserIntegrationError(`${fieldPath} must be an object.`);
  }

  return value as Record<string, unknown>;
}

function asArray(value: unknown, fieldPath: string): unknown[] {
  if (!Array.isArray(value)) {
    throw new DependencyCruiserIntegrationError(`${fieldPath} must be an array.`);
  }

  return value;
}

function asString(value: unknown, fieldPath: string): string {
  if (typeof value !== "string") {
    throw new DependencyCruiserIntegrationError(`${fieldPath} must be a string.`);
  }

  return value;
}

function optionalString(value: unknown): string | undefined {
  return typeof value === "string" ? value : undefined;
}

function optionalNumber(value: unknown): number | undefined {
  return typeof value === "number" && Number.isFinite(value) ? value : undefined;
}
