import { formatPolicyReference, type EffectiveHarnessModel } from "../model/effective-model.js";

export const DEPENDENCY_CRUISER_TARGET_FILE = ".dependency-cruiser.cjs";

const dependencyCruiserEngine = "dependency-cruiser";
const dependencyCruiserRenderer = "dependency-cruiser-config";

type DependencyCruiserSeverity = "error" | "info" | "warn";
type NormalizedViolationSeverity = "advisory" | "error" | "warning";

export type DependencyCruiserForbiddenRule = {
  comment: string;
  from: {
    path: string;
  };
  name: string;
  severity: DependencyCruiserSeverity;
  to: {
    path: string;
  };
};

export type DependencyCruiserConfig = {
  forbidden: DependencyCruiserForbiddenRule[];
  options: {
    combinedDependencies: boolean;
    doNotFollow: {
      path: string[];
    };
    enhancedResolveOptions: {
      conditionNames: string[];
      exportsFields: string[];
      extensions: string[];
    };
    tsPreCompilationDeps: boolean;
  };
};

export type DependencyCruiserImplementationContract = {
  engine: typeof dependencyCruiserEngine;
  language: "typescript";
  renderer: typeof dependencyCruiserRenderer;
};

export type DependencyCruiserCommandMetadata = {
  args: string[];
  configFile: typeof DEPENDENCY_CRUISER_TARGET_FILE;
  engine: typeof dependencyCruiserEngine;
  executable: "depcruise";
  inputPaths: string[];
  outputType: "json";
  resultMapper: "dependency-cruiser-json";
};

export type DependencyCruiserResult = {
  engine: typeof dependencyCruiserEngine;
  ok: boolean;
  summary: {
    advisory: number;
    error: number;
    totalCruised: number;
    totalDependenciesCruised?: number;
    warning: number;
  };
  violations: DependencyCruiserViolation[];
};

export type DependencyCruiserViolation = {
  engine: typeof dependencyCruiserEngine;
  from: string;
  message: string;
  policyId?: string;
  rawSeverity: string;
  ruleName: string;
  severity: NormalizedViolationSeverity;
  to: string;
};

export class DependencyCruiserIntegrationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "DependencyCruiserIntegrationError";
  }
}

export const dependencyCruiserImplementationContract: DependencyCruiserImplementationContract = {
  engine: dependencyCruiserEngine,
  language: "typescript",
  renderer: dependencyCruiserRenderer,
};

export function createDependencyCruiserConfig(
  model: EffectiveHarnessModel,
): DependencyCruiserConfig {
  const implementation = getDependencyCruiserImplementation(model);
  const policy = getImplementedPolicy(model, implementation);
  const policyReference = formatPolicyReference(implementation.policy);
  const boundaries = [...model.boundaries].sort((left, right) =>
    left.name.localeCompare(right.name),
  );
  const severity = toDependencyCruiserSeverity(policy.severity);
  const forbidden = boundaries.flatMap((sourceBoundary) => {
    const allowedDependencies = new Set(model.allowedDependencies[sourceBoundary.name] ?? []);

    return boundaries.flatMap((targetBoundary): DependencyCruiserForbiddenRule[] => {
      if (sourceBoundary.name === targetBoundary.name) {
        return [];
      }

      assertPublicApiWithinBoundary(targetBoundary);

      if (!allowedDependencies.has(targetBoundary.name)) {
        return [
          {
            comment: `${sourceBoundary.name} does not declare ${targetBoundary.name} as an allowed boundary dependency.`,
            from: {
              path: boundaryPathPattern(sourceBoundary.path),
            },
            name: ruleName(
              policyReference,
              sourceBoundary.name,
              targetBoundary.name,
              "undeclared-dependency",
            ),
            severity,
            to: {
              path: boundaryPathPattern(targetBoundary.path),
            },
          },
        ];
      }

      return [
        {
          comment: `${sourceBoundary.name} may depend on ${targetBoundary.name} only through ${targetBoundary.publicApi}.`,
          from: {
            path: boundaryPathPattern(sourceBoundary.path),
          },
          name: ruleName(
            policyReference,
            sourceBoundary.name,
            targetBoundary.name,
            "internal-import",
          ),
          severity,
          to: {
            path: boundaryInternalPathPattern(targetBoundary.path, targetBoundary.publicApi),
          },
        },
      ];
    });
  });

  return {
    forbidden,
    options: {
      combinedDependencies: true,
      doNotFollow: {
        path: ["node_modules"],
      },
      enhancedResolveOptions: {
        conditionNames: ["import", "require", "node", "default", "types"],
        exportsFields: ["exports"],
        extensions: [".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs", ".json"],
      },
      tsPreCompilationDeps: true,
    },
  };
}

export function renderDependencyCruiserConfig(model: EffectiveHarnessModel): string {
  return [
    "// Generated by Architect Companion. Edit .architect-companion/ instead.",
    "/** @type {import('dependency-cruiser').IConfiguration} */",
    `module.exports = ${JSON.stringify(createDependencyCruiserConfig(model), null, 2)};`,
    "",
  ].join("\n");
}

export function getDependencyCruiserCommandMetadata(
  model: EffectiveHarnessModel,
): DependencyCruiserCommandMetadata {
  const inputPaths = Array.from(new Set(model.boundaries.map((boundary) => boundary.path))).sort(
    (left, right) => left.localeCompare(right),
  );

  return {
    args: ["--config", DEPENDENCY_CRUISER_TARGET_FILE, "--output-type", "json", ...inputPaths],
    configFile: DEPENDENCY_CRUISER_TARGET_FILE,
    engine: dependencyCruiserEngine,
    executable: "depcruise",
    inputPaths,
    outputType: "json",
    resultMapper: "dependency-cruiser-json",
  };
}

export function mapDependencyCruiserJsonResult(value: unknown): DependencyCruiserResult {
  const root = asObject(value, "$");
  const summaryRoot = asObject(root.summary, "summary");
  const violations = asArray(summaryRoot.violations, "summary.violations").map(
    (violation, index): DependencyCruiserViolation => {
      const violationPath = `summary.violations[${index}]`;
      const violationRoot = asObject(violation, violationPath);
      const ruleRoot = asObject(violationRoot.rule, `${violationPath}.rule`);
      const ruleNameValue = optionalString(ruleRoot.name) ?? "unnamed";
      const rawSeverity = optionalString(ruleRoot.severity) ?? "warn";
      const comment = optionalString(ruleRoot.comment);
      const from = asString(violationRoot.from, `${violationPath}.from`);
      const to = asString(violationRoot.to, `${violationPath}.to`);
      const policyId = policyIdFromRuleName(ruleNameValue);

      return {
        engine: dependencyCruiserEngine,
        from,
        message: comment ?? `${from} -> ${to} violates ${ruleNameValue}.`,
        ...(policyId === undefined ? {} : { policyId }),
        rawSeverity,
        ruleName: ruleNameValue,
        severity: toNormalizedViolationSeverity(rawSeverity),
        to,
      };
    },
  );

  const summary = {
    advisory: optionalNumber(summaryRoot.info) ?? 0,
    error: optionalNumber(summaryRoot.error) ?? 0,
    totalCruised: optionalNumber(summaryRoot.totalCruised) ?? 0,
    warning: optionalNumber(summaryRoot.warn) ?? 0,
  };
  const totalDependenciesCruised = optionalNumber(summaryRoot.totalDependenciesCruised);

  return {
    engine: dependencyCruiserEngine,
    ok: violations.length === 0,
    summary:
      totalDependenciesCruised === undefined
        ? summary
        : {
            ...summary,
            totalDependenciesCruised,
          },
    violations,
  };
}

function getDependencyCruiserImplementation(
  model: EffectiveHarnessModel,
): EffectiveHarnessModel["implementations"][number] {
  const implementations = model.implementations.filter(
    (implementation) =>
      implementation.engine === dependencyCruiserEngine &&
      implementation.renderer === dependencyCruiserRenderer,
  );

  if (implementations.length === 0) {
    throw new DependencyCruiserIntegrationError(
      `The dependency-cruiser target requires an active ${dependencyCruiserRenderer} implementation.`,
    );
  }

  if (implementations.length > 1) {
    throw new DependencyCruiserIntegrationError(
      `The dependency-cruiser renderer supports exactly one active implementation for now, but found ${implementations.map((implementation) => `"${implementation.sourceProfile}.${implementation.id}"`).join(", ")}.`,
    );
  }

  const [implementation] = implementations;
  if (implementation === undefined) {
    throw new DependencyCruiserIntegrationError(
      `The dependency-cruiser target requires an active ${dependencyCruiserRenderer} implementation.`,
    );
  }

  return implementation;
}

function getImplementedPolicy(
  model: EffectiveHarnessModel,
  implementation: EffectiveHarnessModel["implementations"][number],
): EffectiveHarnessModel["policies"][number] {
  const policy = model.policies.find(
    (candidate) =>
      candidate.sourceProfile === implementation.policy.profile &&
      candidate.id === implementation.policy.id,
  );

  if (policy === undefined) {
    throw new DependencyCruiserIntegrationError(
      `Implementation "${implementation.sourceProfile}.${implementation.id}" references missing policy "${formatPolicyReference(implementation.policy)}".`,
    );
  }

  return policy;
}

function toDependencyCruiserSeverity(
  severity: EffectiveHarnessModel["policies"][number]["severity"],
): DependencyCruiserSeverity {
  switch (severity) {
    case "advisory":
      return "info";
    case "error":
      return "error";
    case "warning":
      return "warn";
  }
}

function toNormalizedViolationSeverity(severity: string): NormalizedViolationSeverity {
  switch (severity) {
    case "error":
      return "error";
    case "info":
      return "advisory";
    case "warn":
      return "warning";
    default:
      return "warning";
  }
}

function assertPublicApiWithinBoundary(
  boundary: EffectiveHarnessModel["boundaries"][number],
): void {
  if (!boundary.publicApi.startsWith(`${boundary.path}/`) && boundary.publicApi !== boundary.path) {
    throw new DependencyCruiserIntegrationError(
      `${boundary.name} public API "${boundary.publicApi}" must be inside boundary path "${boundary.path}" to generate dependency-cruiser rules.`,
    );
  }
}

function boundaryPathPattern(boundaryPath: string): string {
  return `^${escapeRegExp(boundaryPath)}(?:/|$)`;
}

function boundaryInternalPathPattern(boundaryPath: string, publicApiPath: string): string {
  if (boundaryPath === publicApiPath) {
    return `^$`;
  }
  return `^(?!${escapeRegExp(publicApiPath)}$)${escapeRegExp(boundaryPath)}(?:/|$)`;
}

function ruleName(
  policyReference: string,
  sourceBoundary: string,
  targetBoundary: string,
  ruleKind: string,
): string {
  return `architect-companion/${policyReference}/${sourceBoundary}-to-${targetBoundary}/${ruleKind}`;
}

function policyIdFromRuleName(ruleNameValue: string): string | undefined {
  return /^architect-companion\/([^/]+)\//.exec(ruleNameValue)?.[1];
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function asObject(value: unknown, fieldPath: string): Record<string, unknown> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    throw new DependencyCruiserIntegrationError(`${fieldPath} must be an object.`);
  }

  return value as Record<string, unknown>;
}

function asArray(value: unknown, fieldPath: string): unknown[] {
  if (!Array.isArray(value)) {
    throw new DependencyCruiserIntegrationError(`${fieldPath} must be an array.`);
  }

  return value;
}

function asString(value: unknown, fieldPath: string): string {
  if (typeof value !== "string") {
    throw new DependencyCruiserIntegrationError(`${fieldPath} must be a string.`);
  }

  return value;
}

function optionalString(value: unknown): string | undefined {
  return typeof value === "string" ? value : undefined;
}

function optionalNumber(value: unknown): number | undefined {
  return typeof value === "number" && Number.isFinite(value) ? value : undefined;
}
