import { stringify } from "yaml";

import { getArchitectureCheckCommands } from "../checks/architecture-check-commands.js";
import type { EffectiveHarnessModel } from "../model/effective-model.js";

export const GITHUB_ACTIONS_WORKFLOW_PATH = ".github/workflows/architecture.yml";

const generatedHeader = "# Generated by Architect Companion. Edit .architect-companion/ instead.";

export type RenderedGitHubActionsWorkflow = {
  contents: string;
  path: typeof GITHUB_ACTIONS_WORKFLOW_PATH;
};

type GitHubActionsWorkflow = {
  jobs: {
    architecture: {
      name: string;
      "runs-on": string;
      steps: GitHubActionsStep[];
    };
  };
  name: string;
  on: {
    pull_request: Record<string, never>;
    push: {
      branches: string[];
    };
  };
  permissions: {
    contents: string;
  };
};

type GitHubActionsStep =
  | {
      name: string;
      uses: string;
      with?: Record<string, string>;
    }
  | {
      name: string;
      run: string;
    };

export function renderGitHubActionsWorkflow(
  model: EffectiveHarnessModel,
): RenderedGitHubActionsWorkflow {
  const checkSteps = architectureCheckSteps(model);
  const workflow: GitHubActionsWorkflow = {
    name: "Architecture",
    on: {
      pull_request: {},
      push: {
        branches: ["main"],
      },
    },
    permissions: {
      contents: "read",
    },
    jobs: {
      architecture: {
        name: "Architecture checks",
        "runs-on": "ubuntu-latest",
        steps: [
          {
            name: "Check out repository",
            uses: "actions/checkout@v4",
          },
          {
            name: "Set up Node.js",
            uses: "actions/setup-node@v4",
            with: {
              "node-version": "22.x",
              cache: "npm",
            },
          },
          {
            name: "Install dependencies",
            run: "npm ci",
          },
          {
            name: "Verify generated architecture targets",
            run: "npx --no-install architect-companion render --check",
          },
          ...checkSteps,
        ],
      },
    },
  };

  return {
    contents: `${generatedHeader}\n${stringify(workflow, { lineWidth: 0 })}`,
    path: GITHUB_ACTIONS_WORKFLOW_PATH,
  };
}

function architectureCheckSteps(model: EffectiveHarnessModel): GitHubActionsStep[] {
  return getArchitectureCheckCommands(model).map((command) => ({
    name: command.name,
    run: command.run,
  }));
}
