import { stringify } from "yaml";

import {
  formatPolicyReference,
  type EffectiveHarnessModel,
  type KnownTargetKey,
} from "../model/effective-model.js";

export const PR_AGENT_CONFIG_PATH = ".pr_agent.toml";
export const PR_AGENT_WORKFLOW_PATH = ".github/workflows/pr-agent-review.yml";

const generatedHeader = "# Generated by Architect Companion. Edit .architect-companion/ instead.";

type EffectivePolicy = EffectiveHarnessModel["policies"][number];
type EffectiveImplementation = EffectiveHarnessModel["implementations"][number];

/**
 * Maps each policy engine to the target whose selection makes that engine an
 * active CI check. An engine only counts as machine-enforcing a policy when its
 * target is selected; otherwise the policy falls back into the AI rubric. The
 * exhaustive Record forces a mapping decision whenever a new engine is added.
 */
const engineTargetKeys: Record<EffectiveImplementation["engine"], KnownTargetKey> = {
  "dependency-cruiser": "dependencyCruiser",
};

type PrAgentReviewWorkflow = {
  jobs: {
    "pr-architecture-review": {
      if: string;
      name: string;
      permissions: {
        contents: string;
        issues: string;
        "pull-requests": string;
      };
      "runs-on": string;
      steps: PrAgentWorkflowStep[];
    };
  };
  name: string;
  on: {
    issue_comment: Record<string, never>;
    pull_request: {
      types: string[];
    };
  };
};

type PrAgentWorkflowStep = {
  env?: Record<string, string>;
  name: string;
  uses: string;
};

/**
 * Renders both PR-Agent target outputs in the order declared by the target
 * registry: the `.pr_agent.toml` configuration first, then the advisory
 * pull-request workflow.
 */
export function renderPrAgentTarget(model: EffectiveHarnessModel): readonly string[] {
  return [renderPrAgentConfig(model), renderPrAgentReviewWorkflow(model)];
}

/**
 * Renders `.pr_agent.toml`. The architecture rubric is projected into
 * `[pr_reviewer] extra_instructions`, which OSS PR-Agent reads natively for its
 * `/review` tool. Architect Companion only renders this configuration; PR-Agent
 * executes the review as its own CI step.
 */
export function renderPrAgentConfig(model: EffectiveHarnessModel): string {
  // Encode the rubric as a TOML multiline basic string. Escaping backslashes
  // and double quotes keeps arbitrary profile text valid regardless of content
  // (trailing quotes, embedded delimiters, and so on), so rendering never fails.
  const escaped = buildReviewRubric(model).replace(/\\/g, "\\\\").replace(/"/g, '\\"');

  return [generatedHeader, "[pr_reviewer]", 'extra_instructions = """', escaped, '"""', ""].join(
    "\n",
  );
}

/**
 * Renders the advisory pull-request workflow that runs OSS PR-Agent. The model
 * and API key are supplied by the consuming repository through GitHub Actions
 * variables and secrets so the target stays model-agnostic.
 */
export function renderPrAgentReviewWorkflow(_model: EffectiveHarnessModel): string {
  const workflow: PrAgentReviewWorkflow = {
    name: "PR Architecture Review",
    on: {
      issue_comment: {},
      pull_request: {
        types: ["opened", "reopened", "ready_for_review"],
      },
    },
    jobs: {
      "pr-architecture-review": {
        name: "PR architecture review (advisory)",
        // Run on pull-request events for any non-bot author, and on issue
        // comments only when they are a PR command (e.g. /review) — otherwise
        // every PR comment would needlessly start the job.
        if: "${{ github.event.sender.type != 'Bot' && (github.event_name != 'issue_comment' || (github.event.issue.pull_request != null && startsWith(github.event.comment.body, '/'))) }}",
        "runs-on": "ubuntu-latest",
        // Advisory review only: read the code, write PR/issue comments. It must
        // not need contents: write (which would let a malicious PR push code).
        permissions: {
          contents: "read",
          issues: "write",
          "pull-requests": "write",
        },
        steps: [
          {
            name: "Run PR-Agent architecture review",
            uses: "qodo-ai/pr-agent@v0.36.1",
            env: {
              GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}",
              // The model selects the provider via a LiteLLM "provider/model"
              // string; the single LLM_API_KEY secret is wired into each major
              // provider's key variable so the target stays model-agnostic
              // without editing this generated file.
              "config.model": "${{ vars.PR_AGENT_MODEL }}",
              OPENAI_KEY: "${{ secrets.LLM_API_KEY }}",
              "ANTHROPIC.KEY": "${{ secrets.LLM_API_KEY }}",
              "GOOGLE_AI_STUDIO.GEMINI_API_KEY": "${{ secrets.LLM_API_KEY }}",
              "github_action_config.auto_review": "true",
              "github_action_config.auto_describe": "false",
              "github_action_config.auto_improve": "false",
            },
          },
        ],
      },
    },
  };

  return `${generatedHeader}\n${stringify(workflow, { lineWidth: 0 })}`;
}

function buildReviewRubric(model: EffectiveHarnessModel): string {
  const lines: string[] = [
    "You are reviewing a pull request against this project's architecture harness.",
    "Review the diff only against the judgment-only criteria below — the criteria that static analysis cannot check.",
  ];

  const enforced = enforcedPolicies(model);
  if (enforced.length > 0) {
    lines.push(
      "",
      "Already enforced deterministically — do NOT re-review these; defer to the engine's own check:",
    );
    for (const policy of enforced) {
      lines.push(`- ${policy.title} [${policyReference(policy)}] — enforced by dependency-cruiser`);
    }
  }

  if (model.principles.length > 0) {
    lines.push("", "Principles:");
    for (const principle of model.principles) {
      lines.push(`- ${principle.title} (${principle.sourceProfile}): ${principle.guidance}`);
    }
  }

  const policies = judgmentPolicies(model);
  if (policies.length > 0) {
    lines.push("", "Policy intent — flag violations, citing the policy id and severity:");
    for (const policy of policies) {
      lines.push(
        `- ${policy.title} [${policyReference(policy)}] (severity: ${policy.severity}): ${policy.intent}`,
      );
      lines.push(`  ${policy.guidance}`);
    }
  }

  if (model.heuristics.length > 0) {
    lines.push("", "Review heuristics — ask these of the diff:");
    for (const heuristic of model.heuristics) {
      lines.push(`- ${heuristic.title}:`);
      for (const question of heuristic.questions) {
        lines.push(`  - ${question}`);
      }
    }
  }

  lines.push(
    "",
    "For each issue, name the specific principle, policy id, or heuristic it breaks and cite the file and line.",
    "End with an explicit recommendation on whether the pull request is safe to merge.",
  );

  return lines.join("\n");
}

/**
 * Policies that already have an active engine implementation whose target is
 * selected. These are machine-enforced, so the AI reviewer should defer to the
 * engine rather than re-judge them.
 */
function enforcedPolicies(model: EffectiveHarnessModel): EffectivePolicy[] {
  return model.policies.filter((policy) => isMachineEnforced(model, policy));
}

/**
 * The complement: principles and heuristics are always judgment-only, and these
 * are the policies no selected engine enforces. This is the rubric the AI owns.
 */
function judgmentPolicies(model: EffectiveHarnessModel): EffectivePolicy[] {
  return model.policies.filter((policy) => !isMachineEnforced(model, policy));
}

function isMachineEnforced(model: EffectiveHarnessModel, policy: EffectivePolicy): boolean {
  return model.implementations.some(
    (implementation) =>
      implementation.policy.profile === policy.sourceProfile &&
      implementation.policy.id === policy.id &&
      isEngineTargetSelected(model, implementation),
  );
}

function isEngineTargetSelected(
  model: EffectiveHarnessModel,
  implementation: EffectiveImplementation,
): boolean {
  return model.targets[engineTargetKeys[implementation.engine]] === true;
}

function policyReference(policy: EffectivePolicy): string {
  return formatPolicyReference({ id: policy.id, profile: policy.sourceProfile });
}
